#!/usr/bin/env python3
"""
Run the trained model on the actual 2026 NCAA Tournament bracket.

Simulates the full tournament round-by-round using all-pairs predictions
generated by predict.py, combined with the official 2026 bracket seedings.

Usage:
    # After training (python -m src.train --data-dir data/raw) and
    # predicting (python -m src.predict --data-dir data/raw):
    python scripts/run_bracket.py
    python scripts/run_bracket.py --gender M
    python scripts/run_bracket.py --gender W
    python scripts/run_bracket.py --gender both --data-dir data/raw

Outputs:
    predictions/MBracket2026.csv  – round-by-round results for Men's bracket
    predictions/WBracket2026.csv  – round-by-round results for Women's bracket
    docs/data/MBracket2026.json   – same data in JSON for the dashboard
    docs/data/WBracket2026.json   – same data in JSON for the dashboard
"""

import argparse
import json
import os
import sys

import pandas as pd

# Add repo root to path so we can import src modules
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from src.bracket import Bracket, ROUND_POINTS
from src.data_loader import load_seeds

PRED_DIR = os.path.join(REPO_ROOT, "predictions")
DOCS_DATA_DIR = os.path.join(REPO_ROOT, "docs", "data")
os.makedirs(PRED_DIR, exist_ok=True)
os.makedirs(DOCS_DATA_DIR, exist_ok=True)

ROUND_NAMES = {
    0: "First Four",
    1: "First Round (Round of 64)",
    2: "Second Round (Round of 32)",
    3: "Sweet 16",
    4: "Elite Eight",
    5: "Final Four",
    6: "National Championship",
}

SEASON = 2026


def load_team_names(gender="M", data_dir=None):
    """Load a mapping from TeamID → TeamName from the raw data."""
    from src.data_loader import _load
    try:
        teams = _load(f"{gender}Teams.csv", data_dir)
        return dict(zip(teams["TeamID"], teams["TeamName"]))
    except FileNotFoundError:
        return {}


def run_bracket_simulation(gender="M", data_dir=None):
    """
    Load 2026 seeds + all-pairs predictions, simulate the bracket,
    and return structured round-by-round results.

    Returns
    -------
    dict with keys:
        gender, season, rounds (list of round dicts)
    """
    print(f"\n{'='*60}")
    print(f"Simulating {gender} 2026 NCAA Tournament Bracket")
    print(f"{'='*60}")

    # ------------------------------------------------------------------
    # Load 2026 seeds
    # ------------------------------------------------------------------
    raw_dir = data_dir or os.path.join(REPO_ROOT, "data", "raw")
    try:
        seeds_df = load_seeds(gender, raw_dir)
    except FileNotFoundError:
        seeds_df = load_seeds(gender)  # fallback to sample

    seeds_2026 = seeds_df[seeds_df["Season"] == SEASON].copy()
    if seeds_2026.empty:
        print(f"  ERROR: No 2026 seeds found in data for {gender}.")
        print("  Run: python scripts/add_2026_seeds.py  (or check data/raw/)")
        return None

    print(f"  Loaded {len(seeds_2026)} seed entries for {SEASON}.")

    # ------------------------------------------------------------------
    # Load all-pairs predictions (must already be generated)
    # ------------------------------------------------------------------
    pred_file = os.path.join(PRED_DIR, f"{gender}NCAATourneyPredictions.csv")
    if not os.path.exists(pred_file):
        print(f"  ERROR: Predictions file not found: {pred_file}")
        print("  Run: python -m src.predict --data-dir data/raw")
        return None

    pred_df = pd.read_csv(pred_file)
    print(f"  Loaded {len(pred_df):,} all-pairs predictions.")

    # ------------------------------------------------------------------
    # Load team names for readable output
    # ------------------------------------------------------------------
    team_names = load_team_names(gender, raw_dir)
    if not team_names:
        team_names = load_team_names(gender)  # fallback

    def name(tid):
        return team_names.get(int(tid), str(int(tid)))

    # ------------------------------------------------------------------
    # Build Bracket and simulate
    # ------------------------------------------------------------------
    bracket = Bracket(seeds_2026, gender=gender)
    bracket.add_predictions(pred_df)
    games = bracket.simulate_regular_bracket()

    print(f"  Simulated {len(games)} tournament games.")

    # ------------------------------------------------------------------
    # Organise into rounds
    # ------------------------------------------------------------------
    by_round = {}
    for round_num, t1, t2, winner in games:
        by_round.setdefault(round_num, []).append({
            "team1_id": int(t1),
            "team1_name": name(t1),
            "team2_id": int(t2),
            "team2_name": name(t2),
            "predicted_winner_id": int(winner),
            "predicted_winner_name": name(winner),
            "round_points": ROUND_POINTS.get(round_num, 1),
        })

    # Print results
    for rnd in sorted(by_round.keys()):
        print(f"\n  {ROUND_NAMES.get(rnd, f'Round {rnd}')}:")
        for g in by_round[rnd]:
            print(
                f"    {g['team1_name']:>25} vs {g['team2_name']:<25}  →  "
                f"▶ {g['predicted_winner_name']}"
            )

    # Summary champions
    if 6 in by_round and by_round[6]:
        champ = by_round[6][0]
        print(
            f"\n  🏆 Predicted {gender} National Champion: "
            f"{champ['predicted_winner_name']}"
        )

    result = {
        "gender": gender,
        "season": SEASON,
        "rounds": [
            {
                "round": rnd,
                "round_name": ROUND_NAMES.get(rnd, f"Round {rnd}"),
                "games": by_round[rnd],
            }
            for rnd in sorted(by_round.keys())
        ],
    }
    return result


def save_results(result, gender):
    """Save bracket results as CSV and JSON."""
    if result is None:
        return

    # ------------------------------------------------------------------
    # Flat CSV
    # ------------------------------------------------------------------
    rows = []
    for rnd_info in result["rounds"]:
        for g in rnd_info["games"]:
            rows.append({
                "Round": rnd_info["round"],
                "RoundName": rnd_info["round_name"],
                "Team1ID": g["team1_id"],
                "Team1Name": g["team1_name"],
                "Team2ID": g["team2_id"],
                "Team2Name": g["team2_name"],
                "WinnerID": g["predicted_winner_id"],
                "WinnerName": g["predicted_winner_name"],
                "RoundPoints": g["round_points"],
            })

    csv_df = pd.DataFrame(rows)
    csv_path = os.path.join(PRED_DIR, f"{gender}Bracket2026.csv")
    csv_df.to_csv(csv_path, index=False)
    print(f"\n  Bracket CSV saved to {csv_path}")

    # ------------------------------------------------------------------
    # JSON for dashboard
    # ------------------------------------------------------------------
    json_path = os.path.join(DOCS_DATA_DIR, f"{gender}Bracket2026.json")
    with open(json_path, "w") as f:
        json.dump(result, f, indent=2)
    print(f"  Bracket JSON saved to {json_path}")

    return csv_path, json_path


def main():
    parser = argparse.ArgumentParser(
        description="Simulate the actual 2026 NCAA Tournament bracket"
    )
    parser.add_argument(
        "--gender",
        choices=["M", "W", "both"],
        default="both",
        help="Which tournament to simulate (default: both)",
    )
    parser.add_argument(
        "--data-dir",
        type=str,
        default=None,
        help="Directory containing raw Kaggle data files",
    )
    args = parser.parse_args()

    genders = ["M", "W"] if args.gender == "both" else [args.gender]
    for g in genders:
        result = run_bracket_simulation(g, data_dir=args.data_dir)
        save_results(result, g)

    print("\nDone! To update the dashboard, run:")
    print("  python scripts/export_site_data.py")
    print('  git add -A && git commit -m "Update 2026 bracket predictions" && git push')


if __name__ == "__main__":
    main()
